spring.application.name=backend
server.port=${PORT:8080}

# Database Configuration (MySQL)
spring.datasource.url=jdbc:postgresql://dpg-d7iki0iqqhas739648e0-a.singapore-postgres.render.com:5432/appointment_db_bhnd
spring.datasource.username=appointment_user
spring.datasource.password=UfYZ1Uu9jinTDQe2TB5Z3YiS38qT9O6O

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

# Enable H2 console at /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Allow cross origin requests for local react frontend
spring.web.cors.allowed-origins=http://localhost:5173
